export enum ACTION {
  RECEIVE_SOCKET_MESSAGE,
  RECEIVE_SOCKET_PRIVATE_MESSAGE,
  SEND_SOCKET_MESSAGE,
  SEND_SOCKET_PRIVATE_MESSAGE,
  ADD_SERVER,
  ADD_PRIVATE_MESSAGE,
  ADD_CHANNEL,
  CHANGE_CHANNEL,
  CHANGE_SERVER,
  CHANGE_VIEW,
  CHANGE_PM_USER,
  UPDATE_ACTIVE_USERS,
  UPDATE_ACTIVE_STATE,
  SIGN_IN,
  SIGN_OUT,
  GET_INITIAL_DATA
}
